In [16]:
import pandas as pd

def process_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()

    dataframes = []
    current_data = []
    signal_count = 1
    for line in lines:
        if line.startswith('#,'):
            if current_data:
                df = pd.DataFrame(current_data, columns=[f'Signal {signal_count}', current_data[0][1]])
                df.reset_index(drop=True, inplace=True)
                dataframes.append(df)
                current_data = []
                signal_count += 1
            current_data.append(line.strip().split(','))
        else:
            current_data.append(line.strip().split(','))

    if current_data:
        df = pd.DataFrame(current_data, columns=[f'Signal {signal_count}', current_data[0][1]])
        df.reset_index(drop=True, inplace=True)
        dataframes.append(df)

    result = pd.concat(dataframes, axis=1)
    result = result.iloc[1:]
    return result

In [17]:
df = process_file(r"C:\Users\Trisss\Desktop\Capstone\Caps project\demo_upload\data\20170625")
df

     Signal 1 1498255288 Signal 2 1498344071
1        9627          1     7907          3
2        9638          3     7917          5
3        9650          6     7928          5
4        9661          8     7940          5
5        9671         10     7951          5
...       ...        ...      ...        ...
9196      NaN        NaN   113292       1916
9197      NaN        NaN   113303       1910
9198      NaN        NaN   113314       1901
9199      NaN        NaN   113325       1907
9200      NaN        NaN   113336       1914

[9200 rows x 4 columns]